### ISSUE TITLE
Empty channels open

### ISSUE THREAD

**Issue by coyotte508** [po-devs/po-server-goodies#1035]
Is there a reasoning for keeping registered channels open even though they're empty?

People have autojoin so they join directly in those. They can recreate them easily. But some user searching the list of channels might have it hard to find inhabited channels.

**Comment by Fuzzysqurl** [comment]
Only official channels should be perm in my opinion. I brought this up months ago and I don't recall a single reason to have perm channels. 

how is channel joining and auto join done on android? If you have a predominately android member base it might be difficult to get in the channel.

**Comment by NightfallAlicorn** [comment]
Usually people would use /topchannels to find populated ones. I think Android, if I remember correctly, shows all. Even the empty non-perm ones.

I have thought long time back about channels having life span like user alts.

**Comment by Fuzzysqurl** [comment]
Channels with redirects are still cluttering the list. You can't unperm and you can't destroy them. Channels include like "shanaindigo" and "Mafia Channel"

**Comment by Fuzzysqurl** [comment]
Fixed in 570a2b6e3f69e32ef1f6fee89b0d0b8f906a11c5
