### ISSUE TITLE
Remove dumb coin/casino/wall/throw commands?

### ISSUE THREAD

**Issue by Fuzzysqurl** [po-devs/po-server-goodies#1036]
They serve no real purpose. It promotes spamming /flip just to get coins to then throw at people or gamble in a casino for no purpose. 

Some of those commands could be useful in Safari or Mafia themes, but instead, they are blacklisted for a dumb feature, which even has a comment before the commands supporting the stupidity. 

Could move it to a plugin, but people don't really use it anyway so that's why I propose just cutting it out.

**Comment by coyotte508** [comment]
Move it to #Blackjack? x)

**Comment by NightfallAlicorn** [comment]
* Could always have /throw generate a random number between 1-10 to reduce people spamming /coin for more.
* Or maybe /throw be used to throw coins earned in Safari were it throws 1 on it own or toss more depending on commandData input.
* For /coin. Maybe have it display to everyone in chat their result.

Just some ideas.

**Comment by StrudelsPO** [comment]
my life is empty without this wtf

**Comment by jinorae** [comment]
^
