### ISSUE TITLE
/indigodeinvite is broken and not needed, can we remove it?

### ISSUE THREAD

**Issue by ScottTM17** [po-devs/po-server-goodies#1354]
So I tried to do "/indigodeinvite xdevo" in Victory Road... This was the result:
In Victory Road:
(23:29:28) ±Chatot: Yttrium is not a member!
(23:29:28) ±Chatot: Scott TM removed Blinky from the channel member list!
(23:29:28) ±Chatot: Ripper Roo is not a member!
(23:29:28) ±Chatot: Ascarotte is not a member!
(23:29:28) ±Chatot: fitzy is not a member!
(23:29:28) ±Chatot: Maribel Hearn is not a member!
(23:29:28) ±Chatot: gengar17 is not a member!
(23:29:28) ±Chatot: Email is not a member!
(23:29:28) ±Chatot: Leviathan is not a member!
(23:29:28) ±Chatot: tol is not a member!
(23:29:28) ±Chatot: Pokemonistan is not a member!
(23:29:28) ±Chatot: Severian is not a member!
(23:29:28) ±Chatot: Stocke is not a member!

In Indigo Plateau:
(23:29:28) Yttrium left the channel.
(23:29:28) Blinky left the channel.
(23:29:28) Ripper Roo left the channel.
(23:29:28) Ascarotte left the channel.
(23:29:28) fitzy left the channel.
(23:29:28) Maribel Hearn left the channel.
(23:29:28) gengar17 left the channel.
(23:29:28) Email left the channel.
(23:29:28) Leviathan left the channel.
(23:29:28) tol left the channel.
(23:29:28) Pokemonistan left the channel.
(23:29:28) Severian left the channel.
(23:29:28) Stocke left the channel.
(23:29:28) ±Dratini: 1 unwanted visitors were kicked...

With /deinvite existing, as well a channel owner being able to remove members at will, can we just get rid of this broken command? I'd do it myself, but I know I'd break something...

**Comment by PokeWorldBW** [comment]
I find it weird that /indigoinvite is restricted to only Indigo Plateau and Victory Road but /indigodeinvite can be used in any channel

**Comment by StrudelsPO** [comment]
done
