### ISSUE TITLE
Rules will not update, despite no apparent issues in scripts.js or on server

### ISSUE THREAD

**Issue by ScottTM17** [po-devs/po-server-goodies#1356]
I've recently done a few changes to the main PO server rules, yet it does not appear to have updated the rules on the server itself.

With edits to other command lists and other seperate scripts going through, could the issue be with either scripts.js or the /updatescripts command?

**Comment by Fuzzysqurl** [comment]
Depends where it is loaded. Stuff like bots and superadmins need eval or a server restart. I get home in about an hour so if no one else looks into it that will be priority.

**Comment by ScottTM17** [comment]
Fuzzy has used eval to get the rules to update, but would it be possible to have the rules stored on a seperate document (rules.js perhaps) that would allow us to edit them and update them on a live server, instead of having to eval the changes or restart the server?

If this is something that might be done, feel free to make it low priority, I shouldn't need to change the rules again anytime soon :P

**Comment by Fuzzysqurl** [comment]
I guess that didn't fix
