### ISSUE TITLE
(23:28:33) Plugins-error on trivia.js: TypeError: Result of expression 'leaderboard[0]' [undefined] is not an object. on line: 1323

### ISSUE THREAD

**Issue by PokeWorldBW** [po-devs/po-server-goodies#1669]
Error when no one is playing. I guess make it check if the leaderboard isn't empty either through leaderboard.length > 0 or leaderboard[0] !== undefined. First way might be better

https://github.com/po-devs/po-server-goodies/blob/df15c637b2fd0afef41a618a97a35fe64f842eba/scripts/trivia.js#L1323

**Comment by StrudelsPO** [comment]
https://github.com/po-devs/po-server-goodies/commit/af4fb2ef

fixed by @ET54321
