### ISSUE TITLE
Start client scripts wiki?

### ISSUE THREAD

**Issue by coyotte508** [po-devs/po-server-goodies#307]
There's already a template & all with current server scripts, and there's client scripts to import from the po wiki.

Plus github wiki is so much easier to edit & manage.

Pretty please crystal? :o

**Comment by NightfallAlicorn** [comment]
Guess we could close this issue now since we got different scripting pages up here:
https://github.com/po-devs/pokemon-online/wiki/Scripts-Home

I've made start on battle scripts but I add more if I start using other functions.
