### ISSUE TITLE
"Session handler error: line 406. TypeError: Result of expression 'SESSION.global()' [undefined] is not an object."

### ISSUE THREAD

**Issue by apatuka** [po-devs/po-server-goodies#860]
Greetings, 

Im trying to install those scripts on linux but with no luck, it gives me this error:

"Session handler error: line 406. TypeError: Result of expression 'SESSION.global()' [undefined] is not an object."

Thanks

**Comment by CrystalMoogle** [comment]
The error should be ignorable and the script should work fine still. I'll
look into fixing it though.
